name: Webscraping

on:
#  schedule:
 #   - cron: "30 * * * *" # Every hour
    workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    # Load Repo and Install R
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: r-lib/actions/setup-r@v2 
      
      
       #Set-up R
      - name: Install Packages
        run: |
          sudo apt install libcurl4-openssl-dev
          R -e 'install.packages("yfR")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("rugarch")'
          R -e 'install.packages("scales")'

      # Run Rscript    
      - name: Scraping
        run: Rscript R/hello.R
#on:
  #schedule:
    #- cron: '0 8 27-30,1-3 6-7 *'  # Executar todos os dias à meia-noite UTC

      #- name: Install packages
        #run: |
          #Rscript -e 'install.packages("tidyverse")'
          #Rscript -e 'install.packages("forecast")'

      #- name: Run time series forecast
        #run: Rscript forecast_script.R

      #- name: Save forecast to CSV
        #run: |
          #mv forecast_results.csv ${{ github.workspace }}/forecast_results.csv

      # Add new files in folders and commit
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin master
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.SENHA }}
          from: joaopedrocf26@gmail.com
          to: j236144@dac.unicamp.br
          subject: Trabalho de Séries
          body: Se você está recebendo isso significa que GANHAMO PORRAAAA
          attachments: ${{ github.workspace }}/data/previsao.csv


