name: Previsão de fechamento

on:
  schedule:
    - cron: "0 18 27,28,29,30,3,4,5 * *" # Every hour
    #workflow_dispatch
    
jobs:
  scrape:
    runs-on: ubuntu-latest
    
    # Load Repo and Install R
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: r-lib/actions/setup-r@v2 
      
      
       #Set-up R
      - name: Install Packages
        run: |
          sudo apt install libcurl4-openssl-dev
          R -e 'install.packages("yfR")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("rugarch")'
          R -e 'install.packages("scales")'

      # Run Rscript    
      - name: Scraping
        run: Rscript R/previsao.R

      # Add new files in folders and commit
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin master
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.SENHA }}
          from: João Formigari - RA 236144
          to: ctrucios@unicamp.br
          subject: (ME607) - Trabalho Final - Previsão de fechamento das Ações GOOG
          body: Segue em anexo a previsão de fechamento para as ações da GOOG, ação listada na NASDAQ e representa a empresa Alphabet. Membros responsáveis pela previsão - Isabella Nascimento Peres da Silva (RA 238015), João Pedro de Campos Formigari (RA 236144) e Pedro Luis Rebollo (RA 217460).
          attachments: ${{ github.workspace }}/data/previsao.csv


